name: Test on Linux distros

on: [push]

jobs:
  arch-20221120:
    name: Arch 20230122.0.120412
    runs-on: ubuntu-latest
    container:
      image: docker://archlinux:base-devel-20230122.0.120412

    steps:
      - name: Pacman Update
        run: |
          pacman-key --init
          pacman -Syu --noconfirm
      - name: Install Deps
        run: |
          pacman -S --noconfirm openssh git make cmake gcc
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Checkout
        run: |
          git clone --recurse-submodules git@github.com:${{ github.repository }}.git repo
      - name: Compile
        run: |
          cd repo
          make main-dbg
      - name: Compile Server Dummy
        run: |
          cd repo/lib/swicc/tool/server-dummy
          make
      - name: Run swSIM
        run: |
          cd repo
          cd ./lib/swicc/tool/server-dummy && ./build/server-dummy.elf 37324 example.txt &
          sleep 4s
          (./build/swsim.elf -f ./out.swiccfs -g ./data/gsm.json) || code=$?; if [ $code -ne 2 ]; then exit $code; fi

  debian-11:
    name: Debian 11
    runs-on: ubuntu-latest
    container:
      image: docker://debian:bullseye

    steps:
      - name: APT Update
        run: |
          apt-get -qq update
      - name: Install Deps
        run: |
          apt-get -qq -y install git make cmake gcc
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Checkout
        run: |
          git clone --recurse-submodules git@github.com:${{ github.repository }}.git repo
      - name: Compile
        run: |
          cd repo
          make main-dbg
      - name: Compile Server Dummy
        run: |
          cd repo/lib/swicc/tool/server-dummy
          make
      - name: Run swSIM
        run: |
          cd repo
          cd ./lib/swicc/tool/server-dummy && ./build/server-dummy.elf 37324 example.txt &
          sleep 4s
          (./build/swsim.elf -f ./out.swiccfs -g ./data/gsm.json) || code=$?; if [ $code -ne 2 ]; then exit $code; fi

  fedora-37:
    name: Fedora 37
    runs-on: ubuntu-latest
    container:
      image: docker://fedora:37

    steps:
      - name: DNF Update
        run: |
          dnf -q check-update || code=$?; if [ $code -ne 0 or $code -ne 100 ]; then exit $code; fi
      - name: Install Deps
        run: |
          dnf -q -y install git make cmake gcc libasan
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Checkout
        run: |
          git clone --recurse-submodules git@github.com:${{ github.repository }}.git repo
      - name: Compile
        run: |
          cd repo
          make main-dbg
      - name: Compile Server Dummy
        run: |
          cd repo/lib/swicc/tool/server-dummy
          make
      - name: Run swSIM
        run: |
          cd repo
          cd ./lib/swicc/tool/server-dummy && ./build/server-dummy.elf 37324 example.txt &
          sleep 4s
          (./build/swsim.elf -f ./out.swiccfs -g ./data/gsm.json) || code=$?; if [ $code -ne 2 ]; then exit $code; fi

  opensuse-leap-15-4:
    name: openSUSE Leap 15.4
    runs-on: ubuntu-latest
    container:
      image: docker://opensuse/leap:15.4

    steps:
      - name: Zypper Update
        run: |
          zypper -nq update
      - name: Install Deps
        run: |
          zypper -nq install git make cmake gcc11
          update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 11
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Checkout
        run: |
          git clone --recurse-submodules git@github.com:${{ github.repository }}.git repo
      - name: Compile
        run: |
          cd repo
          make main-dbg
      - name: Compile Server Dummy
        run: |
          cd repo/lib/swicc/tool/server-dummy
          make
      - name: Run swSIM
        run: |
          cd repo
          cd ./lib/swicc/tool/server-dummy && ./build/server-dummy.elf 37324 example.txt &
          sleep 4s
          (./build/swsim.elf -f ./out.swiccfs -g ./data/gsm.json) || code=$?; if [ $code -ne 2 ]; then exit $code; fi
